### ISSUE TITLE
Error when trying to run custom BMP

### ISSUE THREAD

**Issue by Last-Futurist** [codiren/hoi4-map-generator-fast-mapper#2]
![image](https://github.com/user-attachments/assets/cb5d8bec-e9ff-49bf-bc41-19376f6f0e84)
I tried running a custom BMP and it did not work, it just gave me this, I do not know what to do

**Comment by codiren** [comment]
Send me the custom BMP i will take a look

**Comment by codiren** [comment]
There was a problem where the program would continue running after getting an error, and it was probably reading memory it was not supposed to. Now it's fixed
